### ISSUE TITLE
[CO #3]Investigate TinyMC replacement

### ISSUE THREAD

**Issue by Adeodonne** [ita-social-projects/StreetCode_Client#1018]
* Is is possible to replace with input
* Investigate another, more stable, libraries

**Comment by KateYatsiuk** [comment]
**DOCS of our new rich text editor:** https://quilljs.com/docs/quickstart/

**Comment by KateYatsiuk** [comment]
### **Implementation features:**
- in the character counter below the field there is the number of ACTUAL characters (without html tags)
- characters are counted according to the Microsoft Word pattern - new paragraph and empty line aren't counted, a space symbol is counted
- links which starts with https://streetcode.com.ua are opened in the same tab, the others in a new one
- **a list of keyboard keys** that are available for pressing when the maximum number of characters is reached: 'Backspace', 'Delete', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End'

**_DOCS_ of our new rich text editor for devs:** https://quilljs.com/docs/quickstart/
