### ISSUE TITLE
After streetcode create  redirect to 404 page

### ISSUE THREAD

**Issue by Adeodonne** [ita-social-projects/StreetCode_Client#1233]
After streetcode create redirect to 404 page, but streetcode was successfully created

**Comment by vasylashka** [comment]
It's impossible to reproduce the bug, so it was decided to move it back to backlog in case it will reproduce. I assume, that the reason for this unexpected behaviour was caused by new authorithation logic and It was corrected by fixing other auth-releted bugs.

**Comment by arisssha** [comment]
Not reproducile.
