### ISSUE TITLE
Add Sonarqube on local machine

### ISSUE THREAD

**Issue by DanyilTerentiev** [ita-social-projects/StreetCode_Client#365]

**Comment by KateYatsiuk** [comment]
**Unit Tests Coverage Analysis (13.06.2023):**
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/c6555c4f-b84c-4cee-8860-11de78764dae)
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/c9406b3a-1aea-433b-8c36-d80e15f8080d)
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/08cb414c-215d-4bed-9f46-6f76644c975c)
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/03a5fc0b-760d-43cf-b2ed-0c2fa70d7bbe)
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/d39719d8-722b-4006-a0a0-e9864e144e5f)

**Comment by KateYatsiuk** [comment]
Methods that lack percentages to reach full test coverage are listed below (MediatR only):
[Unit Tests Code Coverage Analysis.pdf](https://github.com/ita-social-projects/StreetCode_Client/files/11745775/Unit.Tests.Code.Coverage.Analysis.pdf)
