### ISSUE TITLE
[Captcha on Contact Us page] Captcha is not highlighted as required for sending the form.

### ISSUE THREAD

**Issue by Tysyatsky** [ita-social-projects/StreetCode_Client#398]
**Environment:** Opera, Google Chrome.
**Reproducible:** always.
**Build found:** commit https://github.com/ita-social-projects/StreetCode_Client/commit/76687e96efa660445ddd703d9499dbe2f7179011

**Preconditions**
Loaded project.

**Steps to reproduce**
1. Go to [Contact Us Page](http://localhost:3000/contact-us)
2. Go to Форма зворотного зв’язку 
3. Enter any value for first and second input field.
4. Do not click on Captcha.
5. Click on "Відправити" button.

**Actual result**
No message was shown about sending/not sending the request and highlighting the captcha as required.

![image](https://github.com/ita-social-projects/StreetCode_Client/assets/77460353/51dd3e01-1520-42b4-85e0-1f61cdfef33d)

**Expected result**
After clicking the button "Відправити" the Captcha should be highlighted as shown below.

![image](https://github.com/ita-social-projects/StreetCode_Client/assets/77460353/63072b20-f466-4757-a5d8-35d203401c44)

**Postconditions**
No specific post conditions.

**User story and test case links**
Epic https://github.com/ita-social-projects/StreetCode/issues/138

**Comment by mozhaieva** [comment]
After clicking the button "Відправити" without 'Я не робот' checkbox the message 'Підтвердьте, що ви не робот' appears.  Test case [#1594](https://github.com/ita-social-projects/StreetCode/issues/1594) - 'Test Cases Pass' status.
