### ISSUE TITLE
Displaying the StreetCode name instead of the person's name

### ISSUE THREAD

**Issue by vvbogdanovih** [ita-social-projects/StreetCode_Client#456]
**Description**
Display the name of the StreetCode instead of the first and last name

### Acceptance Criteria
We need to display "Stretcode name" instead of " first name + last name"

**Epic link**
E.g.: Epic #100 [Epic](https://jira.softserve.academy/browse/100)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

**Comment by KateYatsiuk** [comment]
Please, describe your ticket properly!
